drop table employee if exists
drop table project_details if exists
drop table team_details if exists
create table employee (
employee_id bigint generated by default as identity, 
create_date timestamp, 
employee_first_name varchar(30) not null, 
employee_last_name varchar(30) not null, 
manager_id bigint, 
team_id bigint, 
primary key (employee_id));

create table project_details (project_id bigint generated by default as identity, 
create_date timestamp, 
project_name varchar(30) not null, 
project_start_date timestamp not null, 
parent_project_id bigint, primary key (project_id));

create table team_details (team_id bigint generated by
 default as identity, 
create_date timestamp, 
team_name varchar(30) not null, 
project_id bigint not null, 
primary key (team_id))

alter table employee add constraint UK_dw6a77to5djqueycpna3gg515 unique (employee_first_name)
alter table employee add constraint UK_bpc657tiik1twh93j65xpd9qn unique (employee_last_name)
alter table project_details add constraint UK_5b1gia493vsh8f68pw3fws7r unique (project_name)
alter table team_details add constraint UK_42y7ayw3c7vmpd0yct292vsp5 unique (team_name)
alter table employee add constraint fk_manager_id foreign key (manager_id) references employee
alter table employee add constraint fk_team_id foreign key (team_id) references team_details
alter table project_details add constraint fk_parent_project_id foreign key (parent_project_id) references project_details
alter table team_details add constraint FK_project_id foreign key (project_id) references project_details